services:
  notification-service:
    build: ../MWS-Cloud-Storage_notification  # путь к проекту уведомлений
    container_name: notification-service
    ports:
      - "8082:8082"
    environment:
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: alg.aaa.2212@gmail.com
      SPRING_MAIL_PASSWORD: cjacjzbeswyplztj  # пароль от Gmail
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
    networks:
      - cloud-network

  app:
    image: cloud-storage-app:latest
    container_name: cloud-storage-app
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      notification-service:  # добавить зависимость
        condition: service_started
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/cloud_storage_db
      DB_USERNAME: postgres
      DB_PASSWORD: super_secret_password_123
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MINIO_URL: ${MINIO_URL}
      MINIO_USERNAME: ${MINIO_USERNAME}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
      NOTIFICATION_SERVICE_URL: http://notification-service:8082  # ВАЖНО!
    networks:
      - cloud-network

  postgres:
    image: postgres:15
    container_name: cloud-storage-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cloud-network

  minio:
    image: minio/minio:latest
    container_name: cloud-storage-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cloud-network

volumes:
  postgres-data:
  minio-data:

networks:
  cloud-network:
    driver: bridge