spring:
  main:
    web-application-type: none

  application:
    name: cloud-storage-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

netty:
  enable-logging: false
  enable-https: true
  https-redirect: true
  http-port: 8080
  https-port: 8443
  boss-threads: 1
  worker-threads: 4
  idle-timeout-sec: 60

  start:
    timeout-sec: 5

  shutdown:
    quiet-period-sec: 2
    timeout-sec: 15

cors:
  access-control:
    allow-origin: "http://localhost:5173"
    allow-credentials: true
    max-age: 3600

storage:
  s3:
    url: ${S3_URL}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    region: ${S3_REGION:eu-central-1}
    user-data-bucket:
      name: ${S3_BUCKET_NAME:user-data}
    limits:
      min-file-part-size: 5242880 # 5mb
      max-file-part-size: 33554432 # 32mb
      max-parts-num: 10000


  rest:
    max-aggregated-content-length: 1048576 # 1mb
    file-download-chunk-size: 65536 # 64 kb

  auth:
    access-token-expiration-sec: 900 # 15 min
    refresh-token-expiration-sec: 2592000 # 30 days
    jwt-secret-key: ${JWT_SECRET_KEY}

  quotas:
    default-storage-limit: 10737418240

  state-machine:
    max-retry-count: 3
    file-stale-time-min: 60
    file-throttled-update-interval-sec: 15

  health-check:
    check-interval-seconds: 10
    db-timeout-seconds: 2
    s3-timeout-seconds: 2
    min-free-memory-percent: 0.10

  failsafe-retry:
    max-attempts: 3
    delay-factor: 2.0
    first-delay: 200ms
    max-delay: 1s
    jitter: 0.1

  trash:
    retention-days: 30

notification:
  tariff:
    days-before-expiry: [ 7, 3, 1 ]

  full-threshold: 0.95
  almost-full-threshold: 0.75

  service:
    url: http://localhost:8082