LogTime yes
PidFile /run/clamav/clamd.pid
LocalSocket /run/clamav/clamd.ctl
FixStaleSocket yes
Foreground yes

ScanArchive yes
AlertEncrypted yes
AlertEncryptedArchive yes
AlertEncryptedDoc yes

TCPSocket 3310
TCPAddr 0.0.0.0