LogTime true
PidFile /run/clamav/clamd.pid
LocalSocket /run/clamav/clamd.ctl
FixStaleSocket true
Foreground true

ScanArchive true
AlertEncrypted true
AlertEncryptedArchive true
AlertEncryptedDoc true

TCPSocket 3310
TCPAddr 0.0.0.0