name: Full Check
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  full-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Check Style
        run: mvn fmt:check

      - name: Run All Tests
        run: mvn verify -Dspring-boot.repackage.skip=true